### ISSUE TITLE
Nebari Workflow Controller doesn't work when using an existing ssl certificate

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari-workflow-controller#23]
### Context
Set up a nebari deployment as explained https://www.nebari.dev/nebari-slurm/configuration#custom-tls-certificate.  Then try to [launch a job with jupyter schedluer](https://www.nebari.dev/docs/tutorials/jupyter-scheduler/).  It won't work.  The error I see in the user's jupyterlab pod logs is below.

```python
Traceback (most recent call last):
  File "/opt/conda/envs/default/lib/python3.11/site-packages/jupyter_scheduler/executors.py", line 60, in process
    self.execute()
  
  File "/opt/conda/envs/default/lib/python3.11/site-packages/argo_jupyter_scheduler/executor.py", line 98, in execute
    self.create_workflow()
  
  File "/opt/conda/envs/default/lib/python3.11/site-packages/argo_jupyter_scheduler/executor.py", line 287, in create_workflow
    w.create()
  
  File "/opt/conda/envs/default/lib/python3.11/site-packages/hera/workflows/workflow.py", line 363, in create
    wf = self.workflows_service.create_workflow()
  
  File "/opt/conda/envs/default/lib/python3.11/site-packages/hera/workflows/service.py", line 946, in create_workflow
    resp = self._request()
  
  File "/opt/conda/envs/default/lib/python3.11/site-packages/hera/workflows/service.py", line 106, in _request
    return self.session.request(method, **kwargs)
  
  File "/opt/conda/envs/default/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  
  File "/opt/conda/envs/default/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  
  File "/opt/conda/envs/default/lib/python3.11/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)

requests.exceptions.SSLError: HTTPSConnectionPool(host='nebari.mydomain.com', port=443): 
Max retries exceeded with url: /argo/api/v1/workflows/prod 
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] 
certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
```

### Value and/or benefit

bug fix

**Comment by Adam-D-Lewis** [comment]
I was playing with this today and tried a bunch of things.  Some probably unnecessary, but I wanted to record what I did today that got this mostly working.  I used `SSL_CERT_FILE=~/tls.crt ./argo submit workflow.yaml` and `SSL_CERT_FILE=~/tls.crt ./argo list` as my test commands after downloading the argo workflows cli binary from their github releases.

- I had to get the public cert and bring it locally and set the env var to use it with the argo request or set some other argo related env var to not verify the tls cert (not recommended).
- I set the webhooks[0].clientConfig.caBundle field in the mutating and validating webhook config objects.  
- I added the following to the argo server pod and the nebari-workflow-controller pods.
```
│     volumeMounts:                                                                                                                                                                          │
│     - mountPath: /etc/ssl/certs/tls.crt                                                                                                                                                    │
│       name: ca                                                                                                                                                                             │
│       subPath: tls.crt                                                                                                                                                                     │
```
and
```
│   volumes:                                                                                                                                                                                 │
│   - name: ca                                                                                                                                                                               │
│     secret:                                                                                                                                                                                │
│       defaultMode: 420                                                                                                                                                                     │
│       secretName: nebari-ssl-cert                                                                                                                                                          │
```
and
```
|     env:
│     - name: REQUESTS_CA_BUNDLE                                                                                                                                                             │
│       value: /etc/ssl/certs/tls.crt                                                                                                                                                        │
│     - name: SSL_CERT_FILE                                                                                                                                                                  │
│       value: /etc/ssl/certs/tls.crt                                                                                                                                                        │
```

I then discovered that I needed to use the complete cert chain for the nebari-ssl-cert secret referenced above in order for TLS validation to work correctly.  I think with that it was solved.
